export enum IComponentEvent {
    oncopy = 'oncopy',
    oncut = 'oncut',
    onpaste = 'onpaste',
    onabort = 'onabort',
    onblur = 'onblur',
    oncancel = 'oncancel',
    oncanplay = 'oncanplay',
    onchange = 'onchange',
    onclick = 'onclick',
    onclose = 'onclose',
    ondblclick = 'ondblclick',
    ondrag = 'ondrag',
    ondragend = 'ondragend',

    ondragenter = 'ondragenter',
    ondragleave = 'ondragleave',
    ondragover = 'ondragover',
    ondragstart = 'ondragstart',
    ondrop = 'ondrop',
    onfocus = 'onfocus',
    onformdata = 'onformdata',
    oninput = 'oninput',
    onkeydown = 'onkeydown',
    onkeypress = 'onkeypress',
    onkeyup = 'onkeyup',
    onmousedown = 'onmousedown',
    onmouseenter = 'onmouseenter',
    onmouseleave = 'onmouseleave',
    onmousemove = 'onmousemove',
    onmouseout = 'onmouseout',
    onmouseover = 'onmouseover',
    onmouseup = 'onmouseup',
    onmousewheel = 'onmousewheel'
}